### ISSUE TITLE
Index error

### ISSUE THREAD

**Issue by TakatoG** [jbkerry/OligoDesign#9]
Hi,
Could you teach me why this error happen??

Traceback (most recent call last):
  File "/lustre7/home/t-goto/oligo-0.1.1b/design.py", line 544, in <module>
    c.extract_repeats().calculate_density().write_oligo_info()
  File "/lustre7/home/t-goto/oligo-0.1.1b/tools.py", line 153, in extract_repeats
    oligo_name = parts[4]
IndexError: list index out of range

How to solve it??

**Comment by jbkerry** [comment]
Sorry for not seeing this issue but we've been in contact since via email and I'm assuming this was solved so I will close this issue
